### ISSUE TITLE
How to use script to resize image?

### ISSUE THREAD

**Issue by Bubilas** [maniekx86/webm-resolution#1]
I have no programming experience, 
I am using Windows

Been searching all over how to execute the script to resize all those images but it seems from what I've found is that .sh scripts are made for linux? I tried running the script on Git Bash but it gave me an error (I didn't change the code in the script at all though) 

Would be happy to get some advice or help on this subject!

**Comment by maniekx86** [comment]
Scripts should work in msys2 or Windows Subsystem for Linux. I managed to run resize.sh by only installing bc command in msys2 and changing ffmpeg line to point to ffmpeg executable on Windows. I think Git Bash is missing bc command.
And yes i made this repo more targeted for Linux but how i said these scripts should work on Windows.

**Comment by maniekx86** [comment]
Closing as inactive, i will link this issue in README
